name: BetterClear
version: '${version}'
main: com.lukaos187.betterclear.BetterClear
api-version: '1.15'
commands:
  betterClear:
    description: Clears the players inventory with the given options.
    usage: /betterClear <name> <typeToClear> <placeToClear>
permissions:
  betterclear.clear:
      description: Allows a player to clear an inventory.
      default: true
  betterclear.clear.hotbar:
    description: Allows clearing other players' hotbars.
    default: op
  betterclear.clear.armor:
    description: Allows clearing other players' armor slots.
    default: op
  betterclear.clear.inventory:
    description: Allows clearing other players' main inventory space (no hotbar or armor slots).
    default: op
  betterclear.clear.offhand:
    description: Allows clearing the other players' offhand.
    default: op
  betterclear.clear.all:
    description: Allows clearing other players' inventory completely.
    default: op
  betterclear.clear.everyone:
    description: Allows clearing everyone on the server.
    default: op
